import numpy as np
import random
import matplotlib.pyplot as plt
import generate_line as line

#line.solution02()

obj1 = line.Points(2)
obj2 = line.Points(2)
obj3 = line.Points(2)
obj4 = line.Points(2)
obj5 = line.Points(2)
obj6 = line.Points(2)
obj1.draw()
obj2.draw()
obj3.draw()
obj4.draw()
obj5.draw()
obj6.draw()
obj1 = line.Points(3)
obj2 = line.Points(3)
obj3 = line.Points(3)
obj4 = line.Points(3)
obj5 = line.Points(3)
obj6 = line.Points(3)
obj1.draw()
obj2.draw()
obj3.draw()
obj4.draw()
obj5.draw()
obj6.draw()
obj1 = line.Points(9)
obj2 = line.Points(9)
obj3 = line.Points(9)
obj4 = line.Points(9)
obj5 = line.Points(9)
obj6 = line.Points(9)
obj1.draw()
obj2.draw()
obj3.draw()
obj4.draw()
obj5.draw()
obj6.draw()
